### ISSUE TITLE
Captured image have bad rotation on Samsung S5

### ISSUE THREAD

**Issue by markos85** [lwansbrough/react-native-camera#351] opened 2016-07-29 08:24 UTC
### Steps to reproduce
1. Capture image with Samsung S5

### Expected behaviour
Go to the recent/gallery and you will see that image have bad rotation ( to the left)

### Actual behaviour
An image should be saved as it's captured, in portrait mode.

### Environment
- **React Native version**: 0.30
- **React Native platform + platform version**: Android 5.0

### react-native-camera
**Version**: 0.3.8

**Comment by charpeni** [comment] 2016-08-02 19:59
Thank you for reporting.

I'll close this issue since it's a duplicate of #309.

**Closed by charpeni** 2016-08-02 19:59 UTC
