### ISSUE TITLE
Captured image have wrong orientation on Samsung S5

### ISSUE THREAD

**Issue by markos85** [lwansbrough/react-native-camera#352] opened 2016-07-29 08:29 UTC
It seems that param orientation doesn't work at all on the Samsung S5 device. Whatever orientation value is passed to native, it doesn't work. The image is always in same, wrong orientation.

### Steps to reproduce
1. Capture image with Samsung S5

### Expected behaviour
Go to the recent/gallery and you will see that image have wrong orientation ( to the left)

### Actual behaviour
An image should be saved as it's captured, in portrait mode.

### Environment
- **React Native version**: 0.30
- **React Native platform + platform version**: Android 5.0

### react-native-camera
**Version**: 0.3.8

**Comment by jakegardner** [comment] 2016-07-29 09:14
experiencing the same thing on ios sim/iphone.

**Comment by charpeni** [comment] 2016-08-02 19:59
Thank you for reporting.

I'll close this issue since it's a duplicate of #309.

**Closed by charpeni** 2016-08-02 19:59 UTC

**Comment by npomfret** [comment] 2017-04-26 08:54
@markos85  are you able to test my PR?  It may help with this https://github.com/lwansbrough/react-native-camera/pull/682.
